server:
  port:8080
spring:
  #数据源 数据据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    #   数据库用户名
    username: root
    password: root

  #模板引擎
  thymeleaf:
    #路径前缀
    prefix: classpath:/templates/
    #后缀
    suffix: .html
    #页面缓存
    cache: false

    #编码
    encoding: UTF-8

    mode: HTML5
  #设置静态资源可以被访问
  mvc:
    static-path-pattern: /static/**

mybatis:
  #mybatis映射地址
  mapper-locations: classpath:/mapper/*Mapper.xml
  #包路径
  type-aliases-package: com.example.supermarket.bean
